# Generated by Django 5.2.4 on 2025-08-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_count',
            field=models.IntegerField(null=True),
        ),
    ]
